// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package local

import (
	"github.com/dsh2dsh/go-tinylfu"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLFU creates a new instance of MockLFU. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLFU(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLFU {
	mock := &MockLFU{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLFU is an autogenerated mock type for the LFU type
type MockLFU struct {
	mock.Mock
}

type MockLFU_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLFU) EXPECT() *MockLFU_Expecter {
	return &MockLFU_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockLFU
func (_mock *MockLFU) Del(key string) {
	_mock.Called(key)
	return
}

// MockLFU_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockLFU_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - key string
func (_e *MockLFU_Expecter) Del(key interface{}) *MockLFU_Del_Call {
	return &MockLFU_Del_Call{Call: _e.mock.On("Del", key)}
}

func (_c *MockLFU_Del_Call) Run(run func(key string)) *MockLFU_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLFU_Del_Call) Return() *MockLFU_Del_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLFU_Del_Call) RunAndReturn(run func(key string)) *MockLFU_Del_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockLFU
func (_mock *MockLFU) Get(key string) ([]byte, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockLFU_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLFU_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockLFU_Expecter) Get(key interface{}) *MockLFU_Get_Call {
	return &MockLFU_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockLFU_Get_Call) Run(run func(key string)) *MockLFU_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLFU_Get_Call) Return(bytes []byte, b bool) *MockLFU_Get_Call {
	_c.Call.Return(bytes, b)
	return _c
}

func (_c *MockLFU_Get_Call) RunAndReturn(run func(key string) ([]byte, bool)) *MockLFU_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockLFU
func (_mock *MockLFU) Set(item *tinylfu.Item[[]byte]) {
	_mock.Called(item)
	return
}

// MockLFU_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockLFU_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - item *tinylfu.Item[[]byte]
func (_e *MockLFU_Expecter) Set(item interface{}) *MockLFU_Set_Call {
	return &MockLFU_Set_Call{Call: _e.mock.On("Set", item)}
}

func (_c *MockLFU_Set_Call) Run(run func(item *tinylfu.Item[[]byte])) *MockLFU_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *tinylfu.Item[[]byte]
		if args[0] != nil {
			arg0 = args[0].(*tinylfu.Item[[]byte])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLFU_Set_Call) Return() *MockLFU_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLFU_Set_Call) RunAndReturn(run func(item *tinylfu.Item[[]byte])) *MockLFU_Set_Call {
	_c.Run(run)
	return _c
}
