dir: "internal/mocks/{{.SrcPackageName}}"
filename: "mock_{{.InterfaceName}}.go"
template: "testify"
packages:
  "github.com/dsh2dsh/expx-cache":
    interfaces:
      "LocalCache":
      "RedisCache":
  "github.com/dsh2dsh/expx-cache/local":
    interfaces:
      "LFU":
  "github.com/dsh2dsh/expx-cache/redis":
    interfaces:
      "Cmdable":
        config:
          template-data:
            unroll-variadic: false
  "github.com/redis/go-redis/v9":
    interfaces:
      "Pipeliner":
