dir: "mocks/{{.PackageName}}"
disable-version-string: True
with-expecter: True
packages:
  github.com/dsh2dsh/expx-cache:
    interfaces:
      LFU:
      LocalCache:
      RedisClient:
  github.com/redis/go-redis/v9:
    interfaces:
      Cmdable:
        config:
          unroll-variadic: False
      Pipeliner:
