// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package cache

import (
	"context"
	"iter"
	"sync"
	"time"

	"github.com/dsh2dsh/expx-cache-redis"
)

// Ensure that MoqLocalCache does implement LocalCache.
// If this is not the case, regenerate this file with mockery.
var _ LocalCache = &MoqLocalCache{}

// MoqLocalCache is a mock implementation of LocalCache.
//
//	func TestSomethingThatUsesLocalCache(t *testing.T) {
//
//		// make and configure a mocked LocalCache
//		mockedLocalCache := &MoqLocalCache{
//			DelFunc: func(key string)  {
//				panic("mock out the Del method")
//			},
//			GetFunc: func(key string) []byte {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(key string, data []byte)  {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedLocalCache in code that requires LocalCache
//		// and then make assertions.
//
//	}
type MoqLocalCache struct {
	// DelFunc mocks the Del method.
	DelFunc func(key string)

	// GetFunc mocks the Get method.
	GetFunc func(key string) []byte

	// SetFunc mocks the Set method.
	SetFunc func(key string, data []byte)

	// calls tracks calls to the methods.
	calls struct {
		// Del holds details about calls to the Del method.
		Del []struct {
			// Key is the key argument value.
			Key string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Key is the key argument value.
			Key string
			// Data is the data argument value.
			Data []byte
		}
	}
	lockDel sync.RWMutex
	lockGet sync.RWMutex
	lockSet sync.RWMutex
}

// Del calls DelFunc.
func (mock *MoqLocalCache) Del(key string) {
	if mock.DelFunc == nil {
		panic("MoqLocalCache.DelFunc: method is nil but LocalCache.Del was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockDel.Lock()
	mock.calls.Del = append(mock.calls.Del, callInfo)
	mock.lockDel.Unlock()
	mock.DelFunc(key)
}

// DelCalls gets all the calls that were made to Del.
// Check the length with:
//
//	len(mockedLocalCache.DelCalls())
func (mock *MoqLocalCache) DelCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockDel.RLock()
	calls = mock.calls.Del
	mock.lockDel.RUnlock()
	return calls
}

// ResetDelCalls reset all the calls that were made to Del.
func (mock *MoqLocalCache) ResetDelCalls() {
	mock.lockDel.Lock()
	mock.calls.Del = nil
	mock.lockDel.Unlock()
}

// Get calls GetFunc.
func (mock *MoqLocalCache) Get(key string) []byte {
	if mock.GetFunc == nil {
		panic("MoqLocalCache.GetFunc: method is nil but LocalCache.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedLocalCache.GetCalls())
func (mock *MoqLocalCache) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *MoqLocalCache) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// Set calls SetFunc.
func (mock *MoqLocalCache) Set(key string, data []byte) {
	if mock.SetFunc == nil {
		panic("MoqLocalCache.SetFunc: method is nil but LocalCache.Set was just called")
	}
	callInfo := struct {
		Key  string
		Data []byte
	}{
		Key:  key,
		Data: data,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	mock.SetFunc(key, data)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedLocalCache.SetCalls())
func (mock *MoqLocalCache) SetCalls() []struct {
	Key  string
	Data []byte
} {
	var calls []struct {
		Key  string
		Data []byte
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// ResetSetCalls reset all the calls that were made to Set.
func (mock *MoqLocalCache) ResetSetCalls() {
	mock.lockSet.Lock()
	mock.calls.Set = nil
	mock.lockSet.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *MoqLocalCache) ResetCalls() {
	mock.lockDel.Lock()
	mock.calls.Del = nil
	mock.lockDel.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockSet.Lock()
	mock.calls.Set = nil
	mock.lockSet.Unlock()
}

// Ensure that MoqRedisCache does implement RedisCache.
// If this is not the case, regenerate this file with mockery.
var _ RedisCache = &MoqRedisCache{}

// MoqRedisCache is a mock implementation of RedisCache.
//
//	func TestSomethingThatUsesRedisCache(t *testing.T) {
//
//		// make and configure a mocked RedisCache
//		mockedRedisCache := &MoqRedisCache{
//			DelFunc: func(ctx context.Context, keys []string) error {
//				panic("mock out the Del method")
//			},
//			ExpireFunc: func(ctx context.Context, key string, ttl time.Duration) (bool, error) {
//				panic("mock out the Expire method")
//			},
//			GetFunc: func(ctx context.Context, maxItems int, keys iter.Seq[string]) iter.Seq2[[]byte, error] {
//				panic("mock out the Get method")
//			},
//			ListenFunc: func(ctx context.Context, key string, ready ...func() error) (string, error) {
//				panic("mock out the Listen method")
//			},
//			LockGetFunc: func(ctx context.Context, keySet string, value string, ttl time.Duration, keyGet string) (bool, []byte, error) {
//				panic("mock out the LockGet method")
//			},
//			SetFunc: func(ctx context.Context, maxItems int, items iter.Seq[redis.Item]) error {
//				panic("mock out the Set method")
//			},
//			UnlockFunc: func(ctx context.Context, key string, value string) (bool, error) {
//				panic("mock out the Unlock method")
//			},
//		}
//
//		// use mockedRedisCache in code that requires RedisCache
//		// and then make assertions.
//
//	}
type MoqRedisCache struct {
	// DelFunc mocks the Del method.
	DelFunc func(ctx context.Context, keys []string) error

	// ExpireFunc mocks the Expire method.
	ExpireFunc func(ctx context.Context, key string, ttl time.Duration) (bool, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, maxItems int, keys iter.Seq[string]) iter.Seq2[[]byte, error]

	// ListenFunc mocks the Listen method.
	ListenFunc func(ctx context.Context, key string, ready ...func() error) (string, error)

	// LockGetFunc mocks the LockGet method.
	LockGetFunc func(ctx context.Context, keySet string, value string, ttl time.Duration, keyGet string) (bool, []byte, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, maxItems int, items iter.Seq[redis.Item]) error

	// UnlockFunc mocks the Unlock method.
	UnlockFunc func(ctx context.Context, key string, value string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Del holds details about calls to the Del method.
		Del []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Keys is the keys argument value.
			Keys []string
		}
		// Expire holds details about calls to the Expire method.
		Expire []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// TTL is the ttl argument value.
			TTL time.Duration
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MaxItems is the maxItems argument value.
			MaxItems int
			// Keys is the keys argument value.
			Keys iter.Seq[string]
		}
		// Listen holds details about calls to the Listen method.
		Listen []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Ready is the ready argument value.
			Ready []func() error
		}
		// LockGet holds details about calls to the LockGet method.
		LockGet []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// KeySet is the keySet argument value.
			KeySet string
			// Value is the value argument value.
			Value string
			// TTL is the ttl argument value.
			TTL time.Duration
			// KeyGet is the keyGet argument value.
			KeyGet string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MaxItems is the maxItems argument value.
			MaxItems int
			// Items is the items argument value.
			Items iter.Seq[redis.Item]
		}
		// Unlock holds details about calls to the Unlock method.
		Unlock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value string
		}
	}
	lockDel     sync.RWMutex
	lockExpire  sync.RWMutex
	lockGet     sync.RWMutex
	lockListen  sync.RWMutex
	lockLockGet sync.RWMutex
	lockSet     sync.RWMutex
	lockUnlock  sync.RWMutex
}

// Del calls DelFunc.
func (mock *MoqRedisCache) Del(ctx context.Context, keys []string) error {
	if mock.DelFunc == nil {
		panic("MoqRedisCache.DelFunc: method is nil but RedisCache.Del was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Keys []string
	}{
		Ctx:  ctx,
		Keys: keys,
	}
	mock.lockDel.Lock()
	mock.calls.Del = append(mock.calls.Del, callInfo)
	mock.lockDel.Unlock()
	return mock.DelFunc(ctx, keys)
}

// DelCalls gets all the calls that were made to Del.
// Check the length with:
//
//	len(mockedRedisCache.DelCalls())
func (mock *MoqRedisCache) DelCalls() []struct {
	Ctx  context.Context
	Keys []string
} {
	var calls []struct {
		Ctx  context.Context
		Keys []string
	}
	mock.lockDel.RLock()
	calls = mock.calls.Del
	mock.lockDel.RUnlock()
	return calls
}

// ResetDelCalls reset all the calls that were made to Del.
func (mock *MoqRedisCache) ResetDelCalls() {
	mock.lockDel.Lock()
	mock.calls.Del = nil
	mock.lockDel.Unlock()
}

// Expire calls ExpireFunc.
func (mock *MoqRedisCache) Expire(ctx context.Context, key string, ttl time.Duration) (bool, error) {
	if mock.ExpireFunc == nil {
		panic("MoqRedisCache.ExpireFunc: method is nil but RedisCache.Expire was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
		TTL time.Duration
	}{
		Ctx: ctx,
		Key: key,
		TTL: ttl,
	}
	mock.lockExpire.Lock()
	mock.calls.Expire = append(mock.calls.Expire, callInfo)
	mock.lockExpire.Unlock()
	return mock.ExpireFunc(ctx, key, ttl)
}

// ExpireCalls gets all the calls that were made to Expire.
// Check the length with:
//
//	len(mockedRedisCache.ExpireCalls())
func (mock *MoqRedisCache) ExpireCalls() []struct {
	Ctx context.Context
	Key string
	TTL time.Duration
} {
	var calls []struct {
		Ctx context.Context
		Key string
		TTL time.Duration
	}
	mock.lockExpire.RLock()
	calls = mock.calls.Expire
	mock.lockExpire.RUnlock()
	return calls
}

// ResetExpireCalls reset all the calls that were made to Expire.
func (mock *MoqRedisCache) ResetExpireCalls() {
	mock.lockExpire.Lock()
	mock.calls.Expire = nil
	mock.lockExpire.Unlock()
}

// Get calls GetFunc.
func (mock *MoqRedisCache) Get(ctx context.Context, maxItems int, keys iter.Seq[string]) iter.Seq2[[]byte, error] {
	if mock.GetFunc == nil {
		panic("MoqRedisCache.GetFunc: method is nil but RedisCache.Get was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		MaxItems int
		Keys     iter.Seq[string]
	}{
		Ctx:      ctx,
		MaxItems: maxItems,
		Keys:     keys,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, maxItems, keys)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRedisCache.GetCalls())
func (mock *MoqRedisCache) GetCalls() []struct {
	Ctx      context.Context
	MaxItems int
	Keys     iter.Seq[string]
} {
	var calls []struct {
		Ctx      context.Context
		MaxItems int
		Keys     iter.Seq[string]
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *MoqRedisCache) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// Listen calls ListenFunc.
func (mock *MoqRedisCache) Listen(ctx context.Context, key string, ready ...func() error) (string, error) {
	if mock.ListenFunc == nil {
		panic("MoqRedisCache.ListenFunc: method is nil but RedisCache.Listen was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Ready []func() error
	}{
		Ctx:   ctx,
		Key:   key,
		Ready: ready,
	}
	mock.lockListen.Lock()
	mock.calls.Listen = append(mock.calls.Listen, callInfo)
	mock.lockListen.Unlock()
	return mock.ListenFunc(ctx, key, ready...)
}

// ListenCalls gets all the calls that were made to Listen.
// Check the length with:
//
//	len(mockedRedisCache.ListenCalls())
func (mock *MoqRedisCache) ListenCalls() []struct {
	Ctx   context.Context
	Key   string
	Ready []func() error
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Ready []func() error
	}
	mock.lockListen.RLock()
	calls = mock.calls.Listen
	mock.lockListen.RUnlock()
	return calls
}

// ResetListenCalls reset all the calls that were made to Listen.
func (mock *MoqRedisCache) ResetListenCalls() {
	mock.lockListen.Lock()
	mock.calls.Listen = nil
	mock.lockListen.Unlock()
}

// LockGet calls LockGetFunc.
func (mock *MoqRedisCache) LockGet(ctx context.Context, keySet string, value string, ttl time.Duration, keyGet string) (bool, []byte, error) {
	if mock.LockGetFunc == nil {
		panic("MoqRedisCache.LockGetFunc: method is nil but RedisCache.LockGet was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		KeySet string
		Value  string
		TTL    time.Duration
		KeyGet string
	}{
		Ctx:    ctx,
		KeySet: keySet,
		Value:  value,
		TTL:    ttl,
		KeyGet: keyGet,
	}
	mock.lockLockGet.Lock()
	mock.calls.LockGet = append(mock.calls.LockGet, callInfo)
	mock.lockLockGet.Unlock()
	return mock.LockGetFunc(ctx, keySet, value, ttl, keyGet)
}

// LockGetCalls gets all the calls that were made to LockGet.
// Check the length with:
//
//	len(mockedRedisCache.LockGetCalls())
func (mock *MoqRedisCache) LockGetCalls() []struct {
	Ctx    context.Context
	KeySet string
	Value  string
	TTL    time.Duration
	KeyGet string
} {
	var calls []struct {
		Ctx    context.Context
		KeySet string
		Value  string
		TTL    time.Duration
		KeyGet string
	}
	mock.lockLockGet.RLock()
	calls = mock.calls.LockGet
	mock.lockLockGet.RUnlock()
	return calls
}

// ResetLockGetCalls reset all the calls that were made to LockGet.
func (mock *MoqRedisCache) ResetLockGetCalls() {
	mock.lockLockGet.Lock()
	mock.calls.LockGet = nil
	mock.lockLockGet.Unlock()
}

// Set calls SetFunc.
func (mock *MoqRedisCache) Set(ctx context.Context, maxItems int, items iter.Seq[redis.Item]) error {
	if mock.SetFunc == nil {
		panic("MoqRedisCache.SetFunc: method is nil but RedisCache.Set was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		MaxItems int
		Items    iter.Seq[redis.Item]
	}{
		Ctx:      ctx,
		MaxItems: maxItems,
		Items:    items,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, maxItems, items)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedRedisCache.SetCalls())
func (mock *MoqRedisCache) SetCalls() []struct {
	Ctx      context.Context
	MaxItems int
	Items    iter.Seq[redis.Item]
} {
	var calls []struct {
		Ctx      context.Context
		MaxItems int
		Items    iter.Seq[redis.Item]
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// ResetSetCalls reset all the calls that were made to Set.
func (mock *MoqRedisCache) ResetSetCalls() {
	mock.lockSet.Lock()
	mock.calls.Set = nil
	mock.lockSet.Unlock()
}

// Unlock calls UnlockFunc.
func (mock *MoqRedisCache) Unlock(ctx context.Context, key string, value string) (bool, error) {
	if mock.UnlockFunc == nil {
		panic("MoqRedisCache.UnlockFunc: method is nil but RedisCache.Unlock was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value string
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
	}
	mock.lockUnlock.Lock()
	mock.calls.Unlock = append(mock.calls.Unlock, callInfo)
	mock.lockUnlock.Unlock()
	return mock.UnlockFunc(ctx, key, value)
}

// UnlockCalls gets all the calls that were made to Unlock.
// Check the length with:
//
//	len(mockedRedisCache.UnlockCalls())
func (mock *MoqRedisCache) UnlockCalls() []struct {
	Ctx   context.Context
	Key   string
	Value string
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value string
	}
	mock.lockUnlock.RLock()
	calls = mock.calls.Unlock
	mock.lockUnlock.RUnlock()
	return calls
}

// ResetUnlockCalls reset all the calls that were made to Unlock.
func (mock *MoqRedisCache) ResetUnlockCalls() {
	mock.lockUnlock.Lock()
	mock.calls.Unlock = nil
	mock.lockUnlock.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *MoqRedisCache) ResetCalls() {
	mock.lockDel.Lock()
	mock.calls.Del = nil
	mock.lockDel.Unlock()

	mock.lockExpire.Lock()
	mock.calls.Expire = nil
	mock.lockExpire.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockListen.Lock()
	mock.calls.Listen = nil
	mock.lockListen.Unlock()

	mock.lockLockGet.Lock()
	mock.calls.LockGet = nil
	mock.lockLockGet.Unlock()

	mock.lockSet.Lock()
	mock.calls.Set = nil
	mock.lockSet.Unlock()

	mock.lockUnlock.Lock()
	mock.calls.Unlock = nil
	mock.lockUnlock.Unlock()
}
