// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLocalCache creates a new instance of MockLocalCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocalCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocalCache {
	mock := &MockLocalCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocalCache is an autogenerated mock type for the LocalCache type
type MockLocalCache struct {
	mock.Mock
}

type MockLocalCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocalCache) EXPECT() *MockLocalCache_Expecter {
	return &MockLocalCache_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockLocalCache
func (_mock *MockLocalCache) Del(key string) {
	_mock.Called(key)
	return
}

// MockLocalCache_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockLocalCache_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - key string
func (_e *MockLocalCache_Expecter) Del(key interface{}) *MockLocalCache_Del_Call {
	return &MockLocalCache_Del_Call{Call: _e.mock.On("Del", key)}
}

func (_c *MockLocalCache_Del_Call) Run(run func(key string)) *MockLocalCache_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocalCache_Del_Call) Return() *MockLocalCache_Del_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLocalCache_Del_Call) RunAndReturn(run func(key string)) *MockLocalCache_Del_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockLocalCache
func (_mock *MockLocalCache) Get(key string) []byte {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockLocalCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLocalCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockLocalCache_Expecter) Get(key interface{}) *MockLocalCache_Get_Call {
	return &MockLocalCache_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockLocalCache_Get_Call) Run(run func(key string)) *MockLocalCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocalCache_Get_Call) Return(bytes []byte) *MockLocalCache_Get_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockLocalCache_Get_Call) RunAndReturn(run func(key string) []byte) *MockLocalCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockLocalCache
func (_mock *MockLocalCache) Set(key string, data []byte) {
	_mock.Called(key, data)
	return
}

// MockLocalCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockLocalCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - data []byte
func (_e *MockLocalCache_Expecter) Set(key interface{}, data interface{}) *MockLocalCache_Set_Call {
	return &MockLocalCache_Set_Call{Call: _e.mock.On("Set", key, data)}
}

func (_c *MockLocalCache_Set_Call) Run(run func(key string, data []byte)) *MockLocalCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocalCache_Set_Call) Return() *MockLocalCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLocalCache_Set_Call) RunAndReturn(run func(key string, data []byte)) *MockLocalCache_Set_Call {
	_c.Run(run)
	return _c
}
